apiVersion: v1
kind: ConfigMap
metadata:
  name: mitmproxy-config
  labels:
    {{- include "mitmproxy.labels" . | nindent 4 }}
data:
  config.yaml: |-
    {{- (.Values.config | default (.Files.Get "config.yaml")) | nindent 4 }}