{{ if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mitmproxy.fullname" . }}
  labels:
    {{- include "mitmproxy.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{ toYaml .Values.service.ports | nindent 4 }}
  selector:
    {{- include "mitmproxy.selectorLabels" . | nindent 4 }}
{{ end }}
