name: Commit readme to gh-pages

on:
  pull_request:
  push:
    branches:
      - main
    paths:
      - 'README.md'
      - 'LICENSE'

jobs:
  mirror-readme:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Merge changes to gh-pages
        env:
          SOURCE_BRANCH: main
          SOURCE_FILES: ./README.md ./LICENSE
          TARGET_BRANCH: gh-pages
        run: |
          # Configure git
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          
          # Checkout target branch
          echo "Checking out $TARGET_BRANCH..."
          git fetch
          git checkout $TARGET_BRANCH
          ls -al
          
          # Copy files
          echo "Checkout files ($SOURCE_FILES) from $SOURCE_BRANCH to $TARGET_BRANCH..."
          git checkout $SOURCE_BRANCH -- $SOURCE_FILES
          git status
          
          # Commit and push
          echo "Commit and push..."
          git add .
          git diff-index --quiet HEAD || git commit -am "Update README.md and LICENSE"
          git push origin $TARGET_BRANCH
